repository:
  name: website
  description: Contribute to Functions Conf
  topics: conference, functions, faas, serverless, serverlessdays, serverlessTO, serverlessVan
  homepage: https://functions.events
  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
