title: Functions Conf
description: community focused, single track, one day conference that moves away from the hype and focuses on the reality of serverless based solutions

url: https://functions.events

collections_dir: _collections

future: true

exclude:
  - ssl
  - Dockerfile
  - docker-compose.yml

collections:
  events:
    output: true
    permalink: /:path/

  speakers:
    output: true
    permalink: /:path/

  partners:
    output: true
    permalink: /:path/

defaults:
  - scope:
      type: events
    values:
      layout: home

  - scope:
      type: speakers
    values:
      layout: speaker

  - scope:
      type: partners
    values:
      layout: partner

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
