version: '2'

services:
  jekyll:
    command: jekyll serve --livereload --ssl-key ssl/localhost.key --ssl-cert ssl/localhost.crt
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000